// src/components/admin/Products/ProductPDFGenerator.jsx
import React from 'react';
import jsPDF from 'jspdf';
import { FaFilePdf } from 'react-icons/fa';
import './pdfgenerator.css';

const ProductPDFGenerator = ({ product }) => {
  const generatePDF = async () => {
    const doc = new jsPDF();
    const logo = new Image();
    logo.src = '/logo.png'; // public folder

    logo.onload = async () => {
      // === Header ===
      doc.addImage(logo, 'PNG', 15, 10, 25, 25);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(20);
      doc.text('Medicart', 45, 25);

      doc.setDrawColor(200);
      doc.line(10, 38, 200, 38); // line under header

      // === Product Info ===
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(13);
      let y = 50;
      const lineHeight = 8;

      const lines = [
        `Product Name: ${product.name}`,
        `Brand: ${product.brand}`,
        `Category: ${product.category}`,
        `Price: ₹${product.price}`,
        `Availability: ${product.availability ? 'Available' : 'Not Available'}`,
      ];

      lines.forEach((line) => {
        doc.text(line, 15, y);
        y += lineHeight;
      });

      // === Description ===
      if (product.description) {
        y += 5;
        doc.setFont('helvetica', 'bold');
        doc.text('Description:', 15, y);
        doc.setFont('helvetica', 'normal');
        const desc = doc.splitTextToSize(product.description, 180);
        y += 6;
        doc.text(desc, 15, y);
        y += desc.length * 6;
      }

      // === Images Section ===
      if (product.images.length > 0) {
        y += 10;
        doc.setFont('helvetica', 'bold');
        doc.text('Images:', 15, y);
        y += 5;

        let x = 15;
        for (let i = 0; i < product.images.length; i++) {
          const img = new Image();
          img.crossOrigin = 'anonymous';
          img.src = product.images[i];

          await new Promise((resolve) => {
            img.onload = () => {
              doc.addImage(img, 'JPEG', x, y, 40, 40);
              x += 45;
              if ((i + 1) % 4 === 0) {
                x = 15;
                y += 45;
              }
              resolve();
            };
          });
        }
      }

      // === Footer ===
      doc.setDrawColor(220);
      doc.line(10, 280, 200, 280);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.text('Generated by Medicart Admin Panel', 105, 287, { align: 'center' });

      doc.save(`${product.name.replace(/\s+/g, '_')}_details.pdf`);
    };
  };

  return (
    <button
      className="bg-green-600 text-white px-3 py-1 rounded hover:bg-green-700 flex items-center"
      onClick={generatePDF}
      title="Download PDF"
    >
      <FaFilePdf className="mr-1" />
      PDF
    </button>
  );
};

export default ProductPDFGenerator;
